import test from 'node:test';
import assert from 'node:assert/strict';
import { buildArgs } from '../server/ffmpeg';
import { cloneConfig, DEFAULT_CONFIG } from '../shared/defaults';

test('multistream uses one encoder and tee fan-out',()=>{const c=cloneConfig(DEFAULT_CONFIG);c.recording.enabled=false;c.destinations=[{id:'1',name:'A',platform:'twitch',enabled:true,url:'rtmp://a/live',streamKey:'one'},{id:'2',name:'B',platform:'youtube',enabled:true,url:'rtmp://b/live',streamKey:'two'}];const args=buildArgs(c);assert.equal(args.filter(x=>x==='h264_nvenc').length,1);assert.ok(args.includes('tee'));const tee=args.at(-1)!;assert.match(tee,/rtmp:\/\/a\/live\/one/);assert.match(tee,/rtmp:\/\/b\/live\/two/);});

test('scene text source is composed into filter graph',()=>{const c=cloneConfig(DEFAULT_CONFIG);c.scenes[0]!.sources=[{id:'txt',name:'Title',kind:'text',enabled:true,x:40,y:50,width:400,height:100,opacity:1,text:'Hello',fontSize:48,color:'#ffffff'}];const args=buildArgs(c);const graph=args[args.indexOf('-filter_complex')+1]!;assert.match(graph,/drawtext/);assert.match(graph,/Hello/);assert.ok(args.includes('[base1]'));});

test('camera overlay EOF does not stop the base program',()=>{const c=cloneConfig(DEFAULT_CONFIG);c.scenes[0]!.sources=[{id:'cam',name:'Camera',kind:'camera',enabled:true,x:10,y:10,width:640,height:360,opacity:.9,device:'Camera 1'}];const args=buildArgs(c);const graph=args[args.indexOf('-filter_complex')+1]!;assert.match(graph,/overlay=10:10:eof_action=pass:shortest=0/);});

test('one audio source is metered without a second encode or a recording sink by default',()=>{const c=cloneConfig(DEFAULT_CONFIG);c.destinations=[{id:'1',name:'A',platform:'twitch',enabled:true,url:'rtmp://a/live',streamKey:'one'}];c.audio.sources=[{id:'mic',name:'Mic',kind:'microphone',enabled:true,muted:false,volume:0.8,device:'Microphone',filters:[{id:'g',type:'gate',enabled:true}]}];const args=buildArgs(c,'win32');const graph=args[args.indexOf('-filter_complex')+1]!;assert.equal(args.filter(x=>x==='h264_nvenc').length,1);assert.ok(args.includes('-progress'));assert.match(graph,/astats=metadata=1/);assert.match(graph,/lc\.src:value=mic/);assert.match(graph,/volume=0\.800/);assert.doesNotMatch(graph,/amix/);assert.doesNotMatch(graph,/gate/);assert.equal(args.includes('-an'),false);assert.doesNotMatch(args.at(-1)!,/matroska|mp4/);});

test('multiple audio sources mix once and skip kinds that are not captured',()=>{const c=cloneConfig(DEFAULT_CONFIG);c.recording.enabled=true;c.destinations=[{id:'1',name:'A',platform:'twitch',enabled:true,url:'rtmp://a/live',streamKey:'one'}];c.audio.sources=[{id:'mic',name:'Mic',kind:'microphone',enabled:true,muted:false,volume:1,device:'Microphone',filters:[]},{id:'desk',name:'Desktop',kind:'desktop',enabled:true,muted:true,volume:0.5,device:'Speakers',filters:[]},{id:'app',name:'Discord',kind:'application',enabled:true,muted:false,volume:1,device:'Discord',filters:[]},{id:'off',name:'Off',kind:'microphone',enabled:false,muted:false,volume:1,device:'Unused',filters:[]}];const args=buildArgs(c,'win32');const graph=args[args.indexOf('-filter_complex')+1]!;assert.equal(args.filter(x=>x==='h264_nvenc').length,1);assert.ok(args.includes('wasapi'));assert.ok(args.includes('dshow'));assert.match(graph,/amix=inputs=2:duration=longest:dropout_transition=0:normalize=0/);assert.match(graph,/volume=0\.500/);assert.match(graph,/volume=0\[heard1\]/);assert.equal(args.includes('Discord'),false);assert.equal(args.includes('Unused'),false);assert.match(args.at(-1)!,/matroska/);});
