import { createReadStream } from 'node:fs';
import { stat } from 'node:fs/promises';
import { extname, resolve, sep } from 'node:path';
import type { IncomingMessage, ServerResponse } from 'node:http';

export class HttpError extends Error { constructor(readonly status: number, message: string) { super(message); } }
export function json(res: ServerResponse, status: number, data: unknown) { const body = JSON.stringify(data); res.writeHead(status, { 'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Content-Length':Buffer.byteLength(body) }); res.end(body); }
export async function body(req: IncomingMessage) { if (!/^application\/json\b/i.test(req.headers['content-type'] ?? '')) throw new HttpError(415,'JSON required.'); const chunks: Buffer[]=[]; let size=0; for await (const chunk of req) { size += (chunk as Buffer).length; if(size>512*1024) throw new HttpError(413,'Request too large.'); chunks.push(chunk as Buffer); } try { return JSON.parse(Buffer.concat(chunks).toString('utf8')); } catch { throw new HttpError(400,'Invalid JSON.'); } }
export function guard(port: number) { const hosts=new Set([`127.0.0.1:${port}`,`localhost:${port}`,`[::1]:${port}`]); return { host:(req:IncomingMessage)=>hosts.has((req.headers.host??'').toLowerCase()), origin:(req:IncomingMessage)=>{ const o=req.headers.origin; if(!o)return true; try{return hosts.has(new URL(o).host.toLowerCase());}catch{return false;} } }; }
const types:Record<string,string>={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2'};
export async function staticFile(req:IncomingMessage,res:ServerResponse,root:string,pathname:string){ if(req.method!=='GET'&&req.method!=='HEAD')throw new HttpError(405,'Method not allowed.'); let p=decodeURIComponent(pathname); if(p.endsWith('/'))p+='index.html'; const file=resolve(root,`.${p}`); if(!file.startsWith(root+sep))throw new HttpError(404,'Not found.'); const info=await stat(file).catch(()=>undefined); if(!info||!info.isFile())throw new HttpError(404,'Not found.'); res.writeHead(200,{'Content-Type':types[extname(file)]??'application/octet-stream','Content-Length':info.size,'Cache-Control':p.startsWith('/assets/')?'public,max-age=31536000,immutable':'no-cache','X-Content-Type-Options':'nosniff'}); if(req.method==='HEAD')return res.end(); createReadStream(file).pipe(res); }
