import { useEffect, useMemo, useState } from 'preact/hooks';
import { Activity, MessageSquare, Monitor, Radio, Settings2, SlidersHorizontal } from 'lucide-preact';
import type { AppState, BroadcastConfig, ChatMessage, Destination, RuntimeStats } from '../../shared/types';
import { api } from './api';

const fmtTime=(ms:number|null)=>ms?new Date(Date.now()-ms).toISOString().slice(11,19):'00:00:00';
export function App(){const[state,setState]=useState<AppState|null>(null);const[draft,setDraft]=useState<BroadcastConfig|null>(null);const[tab,setTab]=useState('studio');const[error,setError]=useState('');
useEffect(()=>{api.state().then(s=>{setState(s);setDraft(structuredClone(s.config));}).catch(e=>setError(e.message));const es=new EventSource('/api/events');es.addEventListener('runtime',e=>setState(s=>s?{...s,runtime:JSON.parse((e as MessageEvent).data)}:s));es.addEventListener('config',e=>setState(s=>s?{...s,config:JSON.parse((e as MessageEvent).data)}:s));es.addEventListener('chat',e=>setState(s=>s?{...s,chat:[...s.chat.slice(-299),JSON.parse((e as MessageEvent).data)]}:s));return()=>es.close();},[]);
if(!state||!draft)return <div class="boot">{error||'Starting LiteCast…'}</div>;const live=state.runtime.state==='live'||state.runtime.state==='starting';const dirty=JSON.stringify(draft)!==JSON.stringify(state.config);
const save=async()=>{try{const c=await api.save(draft);setState(s=>s&&({...s,config:c}));}catch(e){setError((e as Error).message)}};
return <div class={`app theme-${draft.ui.theme} density-${draft.ui.density}`}><header><div class="brand"><Radio/> <b>LiteCast</b><span>Broadcaster</span></div><div class="runtime"><span class={`dot ${state.runtime.state}`}/>{state.runtime.state.toUpperCase()} · {fmtTime(state.runtime.startedAt)} · {Math.round(state.runtime.fps)} FPS · {Math.round(state.runtime.bitrateKbps)} kbps</div><button class="secondary" disabled={!dirty} onClick={save}>Save</button><button class={live?'danger':'live'} onClick={()=>live?api.stop():api.start()}>{live?'Stop':'Go Live'}</button></header><nav>{[['studio',Monitor,'Studio'],['outputs',Radio,'Outputs'],['chat',MessageSquare,'Unified Chat'],['settings',SlidersHorizontal,'Settings'],['stats',Activity,'Performance']].map(([id,Icon,label]:any)=><button class={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={18}/>{label}</button>)}</nav><main>{tab==='studio'&&<Studio config={draft} set={setDraft} runtime={state.runtime}/>} {tab==='outputs'&&<Outputs config={draft} set={setDraft}/>} {tab==='chat'&&<Chat messages={state.chat}/>} {tab==='settings'&&<Settings config={draft} set={setDraft}/>} {tab==='stats'&&<Stats runtime={state.runtime}/>}</main>{error&&<div class="toast" onClick={()=>setError('')}>{error}</div>}</div>}
function Studio({config,set,runtime}:{config:BroadcastConfig,set:(c:BroadcastConfig)=>void,runtime:RuntimeStats}){return <div class="grid"><section class="preview"><div class="preview-screen"><Monitor size={64}/><h2>Program Preview</h2><p>Capture: {config.capture.kind} · {config.video.width}×{config.video.height} @ {config.video.fps}</p><small>The FFmpeg program output is intentionally not decoded back into the UI yet; this keeps the control surface light.</small></div></section><section class="panel"><h2>Quick controls</h2><Field label="Capture"><select value={config.capture.kind} onChange={e=>set({...config,capture:{...config.capture,kind:(e.currentTarget as HTMLSelectElement).value as any}})}><option value="desktop">Desktop</option><option value="window">Window</option><option value="device">Camera / device</option></select></Field><Field label="Window title"><input value={config.capture.windowTitle} onInput={e=>set({...config,capture:{...config.capture,windowTitle:e.currentTarget.value}})}/></Field><Field label="Audio device"><input placeholder="Exact FFmpeg audio device name" value={config.audio.device} onInput={e=>set({...config,audio:{...config.audio,device:e.currentTarget.value}})}/></Field><p class="muted">PID: {runtime.pid??'—'} · Encoder: {config.video.encoder}</p></section></div>}
function Outputs({config,set}:{config:BroadcastConfig,set:(c:BroadcastConfig)=>void}){const add=()=>set({...config,destinations:[...config.destinations,{id:crypto.randomUUID(),name:'New destination',platform:'custom',enabled:true,url:'rtmp://',streamKey:''}]});const update=(id:string,p:Partial<Destination>)=>set({...config,destinations:config.destinations.map(d=>d.id===id?{...d,...p}:d)});return <section class="panel wide"><div class="row"><div><h2>Multistream outputs</h2><p class="muted">Encode once, fan the same compressed stream to every enabled RTMP endpoint.</p></div><button onClick={add}>+ Destination</button></div>{config.destinations.map(d=><div class="destination"><input type="checkbox" checked={d.enabled} onChange={e=>update(d.id,{enabled:e.currentTarget.checked})}/><input value={d.name} onInput={e=>update(d.id,{name:e.currentTarget.value})}/><select value={d.platform} onChange={e=>update(d.id,{platform:e.currentTarget.value as any})}><option>twitch</option><option>youtube</option><option>kick</option><option>facebook</option><option>custom</option></select><input class="grow" placeholder="RTMP/RTMPS ingest URL" value={d.url} onInput={e=>update(d.id,{url:e.currentTarget.value})}/><input class="grow" type="password" placeholder="Stream key" value={d.streamKey} onInput={e=>update(d.id,{streamKey:e.currentTarget.value})}/><button class="ghost" onClick={()=>set({...config,destinations:config.destinations.filter(x=>x.id!==d.id)})}>×</button></div>)}</section>}
function Chat({messages}:{messages:ChatMessage[]}){return <section class="panel wide"><h2>Unified chat</h2><p class="muted">Twitch and YouTube adapters are available from local chat configuration. Kick/Facebook adapters are capability placeholders until their authentication/webhook requirements are configured.</p><div class="chat">{messages.length===0?<p class="muted">No messages yet.</p>:messages.slice().reverse().map(m=><div class="msg"><b>{m.platform}</b><strong>{m.username}</strong><span>{m.text}</span></div>)}</div></section>}
function Settings({config,set}:{config:BroadcastConfig,set:(c:BroadcastConfig)=>void}){return <div class="grid"><section class="panel"><h2>Video</h2><Field label="Resolution"><div class="inline"><input type="number" value={config.video.width} onInput={e=>set({...config,video:{...config.video,width:+e.currentTarget.value}})}/><span>×</span><input type="number" value={config.video.height} onInput={e=>set({...config,video:{...config.video,height:+e.currentTarget.value}})}/></div></Field><Field label="FPS"><input type="number" value={config.video.fps} onInput={e=>set({...config,video:{...config.video,fps:+e.currentTarget.value}})}/></Field><Field label="Bitrate kbps"><input type="number" value={config.video.bitrateKbps} onInput={e=>set({...config,video:{...config.video,bitrateKbps:+e.currentTarget.value}})}/></Field><Field label="Encoder"><select value={config.video.encoder} onChange={e=>set({...config,video:{...config.video,encoder:e.currentTarget.value as any}})}><option value="nvenc">NVIDIA NVENC</option><option value="qsv">Intel Quick Sync</option><option value="amf">AMD AMF</option><option value="software">Software x264</option></select></Field></section><section class="panel"><h2>Interface</h2><Field label="Theme"><select value={config.ui.theme} onChange={e=>set({...config,ui:{...config.ui,theme:e.currentTarget.value as any}})}><option value="midnight">Midnight</option><option value="oled">OLED</option><option value="light">Light</option></select></Field><Field label="Density"><select value={config.ui.density} onChange={e=>set({...config,ui:{...config.ui,density:e.currentTarget.value as any}})}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></Field><Field label="Recording"><input type="checkbox" checked={config.recording.enabled} onChange={e=>set({...config,recording:{...config.recording,enabled:e.currentTarget.checked}})}/></Field><Field label="Folder"><input value={config.recording.directory} onInput={e=>set({...config,recording:{...config.recording,directory:e.currentTarget.value}})}/></Field></section></div>}
function Stats({runtime}:{runtime:RuntimeStats}){return <div class="cards">{[['State',runtime.state],['FPS',runtime.fps.toFixed(1)],['Bitrate',`${runtime.bitrateKbps.toFixed(0)} kbps`],['Speed',`${runtime.speed.toFixed(2)}×`],['PID',runtime.pid??'—'],['Dropped',runtime.droppedFrames]].map(([k,v])=><section class="stat"><span>{k}</span><b>{v}</b></section>)}</div>}
function Field({label,children}:{label:string,children:any}){return <label class="field"><span>{label}</span>{children}</label>}
